### PR TITLE
Handle a nil payload[:view] in blueprint's renderevent.

### LINKED ISSUE #3: Blueprint RenderEvent with a `payload[:view]` raises `NoMethodError`
When using raw field rendering, without view, it's possible that the Blueprint rendering instrumentation will send a notification with a `nil` value for the `payload[:view]`.

Traceback snippet: 

```
[2016-02-19 21:21:06 +0000 292e74294d61 (33)] ERROR : Error during finish callback for event 'praxis.blueprint.render':
[2016-02-19 21:21:06 +0000 292e74294d61 (33)] ERROR : NoMethodError: undefined method `name' for nil:NilClass
[2016-02-19 21:21:06 +0000 292e74294d61 (33)] ERROR : Debugging backtrace:
/srv/global_resource_service/vendor/bundle/ruby/2.2.0/gems/newrelic-praxis-1.1/lib/newrelic-praxis/praxis_blueprints/render_event.rb:7:in `metric_name'
/srv/global_resource_service/vendor/bundle/ruby/2.2.0/gems/newrelic-praxis-1.1/lib/newrelic-praxis/praxis_blueprints/render_subscriber.rb:29:in `finish'
/srv/global_resource_service/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/fanout.rb:102:in `finish'
```

### PR DESCRIPTION
**Pull request by careo**
Closes #3.

### CODE REVIEW

File: lib/newrelic-praxis/praxis_blueprints/render_event.rb [hunk 1]
```diff
@@ -4,7 +4,11 @@ module Blueprint
       class RenderEvent < Event
 
         def metric_name
-          view_name = self.payload[:view].name
+          view_name = if self.payload[:view]
```
Comment (blanquer) [inline lib/newrelic-praxis/praxis_blueprints/render_event.rb]: since this is called often, should we do

``` ruby
view_name = if view = self.payload[:view]
     view.name
else
    'fields'
end
```

instead?
I guess it is nothing in the grand scheme of things...but...why not? :)

**Comment by blanquer** [comment]
LGTM
